import os

import psycopg
from psycopg.rows import dict_row
from dotenv import load_dotenv


load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")


def get_connection():
    """Create a connection to the PostgreSQL database."""

    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is not configured."
        )

    return psycopg.connect(
        database_url,
        row_factory=dict_row,
    )


def initialize_database():
    """Create the database tables if they don't exist."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS articles (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY
                        PRIMARY KEY,
                    title TEXT NOT NULL,
                    url TEXT NOT NULL UNIQUE,
                    published TEXT,
                    summary TEXT,
                    source TEXT NOT NULL,
                    category TEXT NOT NULL,
                    score DOUBLE PRECISION DEFAULT 0,
                    is_read INTEGER DEFAULT 0,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS digests (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY
                        PRIMARY KEY,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    expires_at TIMESTAMP NOT NULL
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS digest_articles (
                    digest_id INTEGER NOT NULL,
                    article_id INTEGER NOT NULL,

                    PRIMARY KEY (digest_id, article_id),

                    FOREIGN KEY (digest_id)
                        REFERENCES digests(id)
                        ON DELETE CASCADE,

                    FOREIGN KEY (article_id)
                        REFERENCES articles(id)
                        ON DELETE CASCADE
                )
            """)

        connection.commit()

    finally:
        connection.close()


def save_articles(articles: list[dict]):
    """Save articles to the database."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            for article in articles:

                cursor.execute("""
                    INSERT INTO articles (
                        title,
                        url,
                        published,
                        summary,
                        source,
                        category,
                        score
                    )
                    VALUES (
                        %s, %s, %s, %s, %s, %s, %s
                    )

                    ON CONFLICT(url) DO UPDATE SET
                        title = EXCLUDED.title,
                        published = EXCLUDED.published,
                        summary = EXCLUDED.summary,
                        source = EXCLUDED.source,
                        category = EXCLUDED.category,
                        score = EXCLUDED.score
                """, (
                    article["title"],
                    article["url"],
                    article["published"],
                    article["summary"],
                    article["source"],
                    article["category"],
                    article["score"],
                ))

        connection.commit()

    finally:
        connection.close()


def get_top_articles(limit: int = 10):
    """Return the highest-ranked articles."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                SELECT *
                FROM articles
                ORDER BY score DESC
                LIMIT %s
            """, (limit,))

            return cursor.fetchall()

    finally:
        connection.close()


def get_article(article_id: int):
    """Return a single article by ID."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                SELECT *
                FROM articles
                WHERE id = %s
            """, (article_id,))

            return cursor.fetchone()

    finally:
        connection.close()


def get_articles(
    limit=20,
    offset=0,
    category=None,
    source=None,
    search=None,
    is_read=None,
):
    """Return paginated articles with optional filters."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            query = """
                SELECT *
                FROM articles
            """

            conditions = []
            parameters = []

            if category is not None:
                conditions.append("category = %s")
                parameters.append(category)

            if source is not None:
                conditions.append("source = %s")
                parameters.append(source)

            if search:
                conditions.append(
                    "(title ILIKE %s OR summary ILIKE %s)"
                )

                search_term = f"%{search}%"

                parameters.extend([
                    search_term,
                    search_term,
                ])

            if is_read is not None:
                conditions.append("is_read = %s")
                parameters.append(1 if is_read else 0)

            if conditions:
                query += (
                    " WHERE "
                    + " AND ".join(conditions)
                )

            query += """
                ORDER BY score DESC, id DESC
                LIMIT %s
                OFFSET %s
            """

            parameters.extend([
                limit,
                offset,
            ])

            cursor.execute(
                query,
                parameters,
            )

            return cursor.fetchall()

    finally:
        connection.close()


def get_recent_articles(hours: int = 12):
    """Return articles first seen within the last N hours."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                SELECT *
                FROM articles
                WHERE created_at >=
                    CURRENT_TIMESTAMP - (%s * INTERVAL '1 hour')
                ORDER BY score DESC
            """, (hours,))

            return cursor.fetchall()

    finally:
        connection.close()


def create_digest_record(articles: list[dict]):
    """Create a digest and associate articles with it."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                INSERT INTO digests (
                    expires_at
                )
                VALUES (
                    CURRENT_TIMESTAMP
                    + INTERVAL '12 hours'
                )
                RETURNING id
            """)

            digest_id = cursor.fetchone()["id"]

            for article in articles:

                cursor.execute("""
                    INSERT INTO digest_articles (
                        digest_id,
                        article_id
                    )
                    VALUES (%s, %s)
                """, (
                    digest_id,
                    article["id"],
                ))

        connection.commit()

        return digest_id

    finally:
        connection.close()


def get_digests(
    limit: int = 20,
    offset: int = 0,
    digest_id: int | None = None,
):
    """Return recent digests with their associated articles."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            if digest_id is not None:

                cursor.execute("""
                    SELECT id, created_at, expires_at
                    FROM digests
                    WHERE id = %s
                """, (digest_id,))

            else:

                cursor.execute("""
                    SELECT id, created_at, expires_at
                    FROM digests
                    ORDER BY created_at DESC, id DESC
                    LIMIT %s
                    OFFSET %s
                """, (
                    limit,
                    offset,
                ))

            digest_rows = cursor.fetchall()

            digests = []

            for digest in digest_rows:

                cursor.execute("""
                    SELECT
                        a.id,
                        a.title,
                        a.url,
                        a.published,
                        a.summary,
                        a.source,
                        a.category,
                        a.score,
                        a.is_read
                    FROM digest_articles da
                    JOIN articles a
                        ON a.id = da.article_id
                    WHERE da.digest_id = %s
                    ORDER BY a.score DESC
                """, (digest["id"],))

                articles = cursor.fetchall()

                digests.append({
                    "id": digest["id"],
                    "created_at": digest["created_at"],
                    "expires_at": digest["expires_at"],
                    "articles": articles,
                })

            return digests

    finally:
        connection.close()


def get_last_digest_time():
    """Return the timestamp of the most recent digest."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                SELECT created_at
                FROM digests
                ORDER BY created_at DESC
                LIMIT 1
            """)

            result = cursor.fetchone()

            if result is None:
                return None

            return result["created_at"]

    finally:
        connection.close()


def get_articles_since(timestamp: str):
    """Return articles discovered since a given timestamp."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                SELECT *
                FROM articles
                WHERE created_at > %s
                ORDER BY score DESC
            """, (timestamp,))

            return cursor.fetchall()

    finally:
        connection.close()


def get_active_digests():
    """Return all non-expired digests with their articles."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                SELECT
                    d.id AS digest_id,
                    d.created_at,
                    d.expires_at,

                    a.id AS article_id,
                    a.title,
                    a.url,
                    a.published,
                    a.summary,
                    a.source,
                    a.category,
                    a.score

                FROM digests d

                JOIN digest_articles da
                    ON d.id = da.digest_id

                JOIN articles a
                    ON da.article_id = a.id

                WHERE d.expires_at > CURRENT_TIMESTAMP

                ORDER BY
                    d.created_at DESC,
                    a.score DESC
            """)

            rows = cursor.fetchall()

            digests = {}

            for row in rows:

                digest_id = row["digest_id"]

                if digest_id not in digests:
                    digests[digest_id] = {
                        "id": digest_id,
                        "created_at": row["created_at"],
                        "expires_at": row["expires_at"],
                        "articles": [],
                    }

                digests[digest_id]["articles"].append({
                    "id": row["article_id"],
                    "title": row["title"],
                    "url": row["url"],
                    "published": row["published"],
                    "summary": row["summary"],
                    "source": row["source"],
                    "category": row["category"],
                    "score": row["score"],
                })

            return list(digests.values())

    finally:
        connection.close()


def set_article_read_status(
    article_id: int,
    is_read: bool,
):
    """Set whether an article has been read."""

    connection = get_connection()

    try:
        with connection.cursor() as cursor:

            cursor.execute("""
                UPDATE articles
                SET is_read = %s
                WHERE id = %s
            """, (
                1 if is_read else 0,
                article_id,
            ))

            updated = cursor.rowcount > 0

        connection.commit()

        return updated

    finally:
        connection.close()

